# -*- encoding: utf-8 -*-

# Ok Status
GENERIC_OK_STATUS = 0
CREATE_OK_STATUS = 1
DELETE_OK_STATUS = 2
LIST_OK_STATUS = 3
UPDATE_OK_STATUS = 4

# Not Ok Status
ACTION_NOT_FOUND_STATUS = -1
APPOINTMENT_NOT_FOUND_STATUS = -2
BAD_FORMAT_DATE_STATUS = -3
BAD_FORMAT_EMAIL_STATUS = -4
BAD_FORMAT_ID_STATUS = -5
CANT_CREATE_APPOINTMENT_BEFORE_STATUS = -6
CANT_CREATE_APPOINTMENT_STATUS = -7
CANT_DELETE_APPOINTMENT_BEFORE_STATUS = -8
CANT_DELETE_APPOINTMENT_STATUS = -9
CANT_LIST_APPOINTMENTS_STATUS = -10
CANT_UPDATE_APPOINTMENT_BEFORE_STATUS = -11
CANT_UPDATE_APPOINTMENT_STATUS = -12
DATE_NOT_IN_RANGE_STATUS = -13
DUPLICATE_APPOINTMENT_STATUS = -14
MISSING_ACTION_STATUS = -15
MISSING_DATE_STATUS = -16
MISSING_EMAIL_STATUS = -17
MISSING_ID_STATUS = -18
MISSING_TIME_STATUS = -19
PAST_DATE_STATUS = -20
PAST_TIME_STATUS = -21
TIME_NOT_A_NUMBER_STATUS = -22
TIME_NOT_IN_RANGE_STATUS = -23
BROKEN_PIPE_ERROR_STATUS = -24

GENERIC_EXCEPTION_STATUS = -100