"""Insert Actions

Revision ID: 58696719a4c3
Revises: 
Create Date: 2019-04-02 23:45:33.915409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58696719a4c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('old_date', sa.Date(), nullable=True),
    sa.Column('old_time', sa.Integer(), nullable=True),
    sa.Column('old_email', sa.String(length=255), nullable=True),
    sa.Column('new_date', sa.Date(), nullable=True),
    sa.Column('new_time', sa.Integer(), nullable=True),
    sa.Column('new_email', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    op.drop_table('appointment')
    op.drop_table('action')
    # ### end Alembic commands ###
